# Generated by Django 3.1.2 on 2020-12-11 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='formations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att', models.IntegerField(default=0, null=True)),
                ('mid_att', models.IntegerField(default=0, null=True)),
                ('mid_mid', models.IntegerField(default=0, null=True)),
                ('mid_def', models.IntegerField(default=0, null=True)),
                ('deff', models.IntegerField(default=0, null=True)),
                ('gk', models.IntegerField(default=1, null=True)),
                ('name', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField(default='', null=True)),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='msquads.formations')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='saved_squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(default='none', max_length=30, null=True)),
                ('p2', models.CharField(default='none', max_length=30, null=True)),
                ('p3', models.CharField(default='none', max_length=30, null=True)),
                ('p4', models.CharField(default='none', max_length=30, null=True)),
                ('p5', models.CharField(default='none', max_length=30, null=True)),
                ('p6', models.CharField(default='none', max_length=30, null=True)),
                ('p7', models.CharField(default='none', max_length=30, null=True)),
                ('p8', models.CharField(default='none', max_length=30, null=True)),
                ('p9', models.CharField(default='none', max_length=30, null=True)),
                ('p10', models.CharField(default='none', max_length=30, null=True)),
                ('p11', models.CharField(default='none', max_length=30, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='msquads.formations')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
