# Generated by Django 3.1.2 on 2020-12-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msquads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='names',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
